
<MainMenu>:
    Label: 
        text: "Digimon Farm"
        font_size: 80  
        center_x: root.width / 2
        top: root.top - 60
    Button:
        text: "Start"
        top: root.top - 180
        center_x: root.width / 2
        size: 300, 80
        font_size: 50
        on_press: Farm()
    Button: 
        text: "Quit"
        center_x: root.width / 2
        top: root.top - 270
        size: 300, 80
        font_size: 50
        on_press: app.stop()